build:
  maxIssues: 10

complexity:
  TooManyFunctions:
    thresholdInFiles: 20
    thresholdInClasses: 20
    thresholdInInterfaces: 10
    thresholdInObjects: 10
    thresholdInEnums: 5

style:
  MagicNumber:
    active: true
    ignoreNumbers: ['-1', '0', '1', '2', '100', '1000']
  MaxLineLength:
    active: true
    maxLineLength: 120

naming:
  FunctionNaming:
    functionPattern: '^([a-zA-Z$][a-zA-Z0-9$]*)|(`.*`)$'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][_A-Z0-9]*'
    propertyPattern: '[A-Za-z][_A-Za-z0-9]*'
    privatePropertyPattern: '(_)?[A-Za-z][A-Za-z0-9]*'