name: Android CI

on:
  push:
    paths:
      - 'shared/**'
      - 'android/**'
      - '.github/workflows/android-ci.yml'
  pull_request:
    paths:
      - 'shared/**'
      - 'android/**'
      - '.github/workflows/android-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :android:assembleDebug
    - name: Run Tests
      run: ./gradlew :shared:testDebugUnitTest :android:testDebugUnitTest
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug.apk
        path: android/build/outputs/apk/debug/app-debug.apk