name: Android CI

on:
  push:
    branches:
      - develop
      - feature/*
      - bugfix/*
      - release/*
      - hotfix/*
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        android-version: [29, 30, 31]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Android SDK
        uses: actions/setup-android@v3
        with:
          api-level: ${{ matrix.android-version }}
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Install Android SDK
        uses: actions/setup-android@v3
        with:
          api-level: ${{ matrix.android-version }}
      - name: Lint
        run: ./gradlew lint