name: iOS CI

on:
  push:
    paths:
      - 'shared/**'
      - 'ios/**'
      - '.github/workflows/ios-ci.yml'
  pull_request:
    paths:
      - 'shared/**'
      - 'ios/**'
      - '.github/workflows/ios-ci.yml'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Build shared code
      run: ./gradlew :shared:embedAndSignAppleFrameworkForXcode
    - name: Build and Test
      run: |
        cd iosApp
        xcodebuild -project iosApp.xcodeproj -scheme iosApp -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' build test