name: iOS CI

on:
  push:
    paths:
      - 'shared/**'
      - 'ios/**'
      - '.github/workflows/ios-ci.yml'
  pull_request:
    paths:
      - 'shared/**'
      - 'ios/**'
      - '.github/workflows/ios-ci.yml'

jobs:
  build-and-test:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0
        with:
          xcode-version: '15.0'
      - name: Build Shared Code
        run: ./gradlew :shared:assembleRelease
      - name: Build iOS App
        run: xcodebuild build -workspace ios/iosApp.xcworkspace -scheme iosApp
      - name: Test iOS App
        run: xcodebuild test -workspace ios/iosApp.xcworkspace -scheme iosApp
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3