name: Linux CI

on:
  push:
    paths:
      - 'shared/**'
      - 'linux/**'
      - '.github/workflows/linux-ci.yml'
  pull_request:
    paths:
      - 'shared/**'
      - 'linux/**'
      - '.github/workflows/linux-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Shared Code
        run: ./gradlew :shared:assembleRelease
      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ./linux/LinuxApp.csproj
      - name: Build Linux App
        run: dotnet build ./linux/LinuxApp.csproj --no-restore
      - name: Upload Code Coverage (optional)
        uses: codecov/codecov-action@v3