name: Windows CI

on:
  push:
    paths:
      - 'shared/**'
      - 'windows/**'
      - '.github/workflows/windows-ci.yml'
  pull_request:
    paths:
      - 'shared/**'
      - 'windows/**'
      - '.github/workflows/windows-ci.yml'

jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Shared Code
        run: ./gradlew :shared:assembleRelease
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
      - name: Restore dependencies
        run: dotnet restore ./windows/WindowsApp.csproj
      - name: Build Windows App
        run: dotnet build ./windows/WindowsApp.csproj --no-restore
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v3